language: node_js
node_js:
- '12'
script:
- npm run build
deploy:
  provider: heroku
  api_key:
    secure: D+t+XaNErAP8JRi/hDVR2gxPFoTyUNAsSeb8GUOBR1FhG6NiXOt0rCl70y3zpO1TXLfwPmsO7c4rulhXOQvrEhNtEW21HiFpwsxVtwvK3g+/wQW6lZ3XzaEmsp46Jy2XZt8kJcKJ8vf+rRB43f0IuDY+tTqTB0y7h6rYgOeyHYj0mmcILxu/vUkh85eexZxtAzhrR3Ct3p2SQD+/G2X77Ug+/yjbOQHYSZyaHMi8NnmbLPqbvhBKI+LgLHhSkX9JLGBUolfZ+Q+4I7DfHdt8yCPOfLOS2yqg4ua3isonsdRdK9te/tpqlVVEZGXQ51bFmnDSxamPFeS4OfsSL7KSkuQub3s3SGg96d7zmNiqmT4SLNvejhh6BY6RTgGiI/9MSL2rkYLsQFx9UO5UYKrUCzIXryXMdyCzoUuoIjTBH96189c8/WfgGF6I9j8iPWl/rQf+BpXdPU92KonUFWvXUsEBOq9ky76YjP9DEwynMDpDBJp6ZYWy/o7gB+Xmqv7FBc/s/B+rkOVkYWuOS51llw2c4DbLcO/Bb7CJbb9ltOa+z8kt3vLFZurvqr+pck3WSnyMcKD4M/F+dZNFbc8JzJVJ57yzQWlK2Gkc/j+4QkPeGv7cr0jHda5WCdU7S79WUcpxzfqOHtjNuOu6QjlwcCzcOddIV2X6CfJdtWssKqQ=
  app: chingqueue
  on:
    repo: adriapa-oocl/chingqueue-frontend
